events {
    worker_connections 1024;
}

http {
    upstream kong_proxy {
        server kong:8000;
    }

    upstream kong_admin {
        server kong:8001;
    }

    server {
        listen 8000;
        
        location / {
            proxy_pass http://kong_proxy;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 8001;
        
        location / {
            proxy_pass http://kong_admin;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
